name: Generate and Store Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version (e.g., v2.13)'
        required: true
        default: 'v2.13'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create the release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby for Asciidoctor
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or any recent version
          bundler-cache: true

      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Create release notes build directory
        run: mkdir release-notes-build

      - name: Convert AsciiDoc to HTML
        run: |
          VERSION=${{ inputs.version }}
          INPUT_FILE="versions/${VERSION}/modules/en/pages/release-notes/${VERSION}.adoc"
          OUTPUT_FILE="release-notes-build/${VERSION}.html"

          if [ ! -f "$INPUT_FILE" ]; then
            echo "Error: Input file $INPUT_FILE not found."
            exit 1
          fi

          asciidoctor -v -o "$OUTPUT_FILE" "$INPUT_FILE"

      - name: Convert HTML to GitHub-Flavored Markdown
        run: |
          VERSION=${{ inputs.version }}
          HTML_FILE="release-notes-build/${VERSION}.html"
          MARKDOWN_FILE="release-notes-build/${VERSION}.md"

          pandoc --from html-native_divs \
                 --to gfm \
                 --lua-filter=./.github/workflows/filters/admonition-filter.lua \
                 --output "$MARKDOWN_FILE" \
                 "$HTML_FILE"

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push HTML and Markdown to release-notes-build branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-notes-build
          force: true
          directory: release-notes-build
